In [1]:
import numpy as np

In [2]:
arr=np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
A=np.sqrt(arr)

In [10]:
A

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
A

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [7]:
B=np.exp(arr)

In [8]:
B

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [9]:
np.maximum(A,B)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [11]:
np.add(A,B)

array([1.00000000e+00, 3.71828183e+00, 8.80326966e+00, 2.18175877e+01,
       5.65981500e+01, 1.50649227e+02, 4.05878283e+02, 1.09927891e+03,
       2.98378641e+03, 8.10608393e+03, 2.20296281e+04])

In [16]:
website='https://docs.scipy.org/doc/numpy/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True